name: sporify
flutter: 
  uses-material-design: true
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-14.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
    
  flutter_localizations: # Add this line
    sdk: flutter 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed: ^1.1.1

  #ui
  carousel_slider: ^4.0.0

  #storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0

  #architecture
  flutter_bloc: ^7.2.0
  

  #rx
  rxdart: ^0.27.3

  #network
  http: ^0.13.4
  flutter_web_auth: ^0.4.0
  oauth2: ^2.0.0
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.4
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generation
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3

  #retrofit
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4